### ISSUE TITLE
jRCTからもUMIN-CTRと同様に情報を取りたい

### ISSUE THREAD

**Issue by tosh13** [nnh/research_management#1]
https://jrct.niph.go.jp/detail/645 の
　対象疾患名
　介入の内容
を
臨床研究実施計画番号　jRCTs031180038
より 取得したい

**Comment by R-Y** [comment]
@tosh13 
その「臨床研究実施計画番号」はBaseシートのK列(CTR)のデータを参照すれば良いのでしょうか？
また、取ってきた情報をどのシートのどの列に入れれば良いのでしょうか？

**Comment by tosh13** [comment]
> その「臨床研究実施計画番号」はBaseシートのK列(CTR)のデータを参照すれば良いのでしょうか？
はい、そうです。

> また、取ってきた情報をどのシートのどの列に入れれば良いのでしょうか？
UMIN-CTRと同じ場所に入れていただければと思います。jCRTと両方番号が付いている場合にはUMIN-CTRを優先してもらえればと思います。

**Comment by katsusuke** [comment]
- 医薬品・医療機器等を用いた侵襲及び介入を伴う臨床研究であることの説明等
  - JRCT から取得したい
  - NHOH-PTCL-GDPR 等が動くようにしたい
  - CTR 列で検索する
  - 対象疾患名
  - 介入の内容 / Intervention(s) 
    - 2 + 1 + をクリックで見れる
  - https://jrct.niph.go.jp/latest-detail/jRCTs031180445

**Comment by katsusuke** [comment]
@tosh13 反映いたしましたご確認お願いします
